setwd("/Users/gujaeseo/Documents/projects/yeonseo/ijim_research_2026")
load("previous_resource/ISR_submitted ver_data.RData")
cat("=== matched_data1 columns ===\n")
print(names(matched_data1))
cat("\n=== matched_data1 head ===\n")
print(head(matched_data1, 3))
cat("\n=== psmatch1 covariates ===\n")
print(names(psmatch1$X))
cat("\n=== Treat split in matched_data1 ===\n")
print(table(matched_data1$Treat))
